### ISSUE TITLE
win10系统make不通过

### ISSUE THREAD

**Issue by LucasParker520** [bobwenstudy/easy_button#1]
# 环境：win10系统，vscode，安装了conda、git等一些乱七八糟的东西。
# 问题总结（个人认为）
- 在有些win10系统上，使用cmd.exe执行该make命令时会出现错误，如两个echo只输出一个，不能mkdir创建目录等问题。
- 使用vscode时，其会默认选择支持linux指令的sh去执行make命令，但此时依然存在$@为空的情况，改用mkdir -p可以解决该问题。
# 问题描述：
- 下载工程后，make不通过。于是调试找问题，发现命令makefile中命令有时执行不正常，两个echo只输出一个，如下图：
  ![image](https://github.com/user-attachments/assets/799d5ee9-1a28-4b39-b13d-d4bb4a833f6e)
- 问chatGPT，得知可能是shell设置问题：
    ![image](https://github.com/user-attachments/assets/648e535f-9f1c-4922-8610-e7d679912dd8)
- 于是将以上代码注释掉，发现可以输出两个echo了，代码正常执行。
    ![image](https://github.com/user-attachments/assets/61fb88df-d0e8-466c-8258-33d5a7ac6996)
- 但是发现此时vscode默认选择到POSIX兼容的sh，导致在检查目录是否存在、创建目录时语法错误，简而言之，是 "$@"一直为空，导致出错。
    ![image](https://github.com/user-attachments/assets/9ebc00c6-ce52-4fa4-acc3-b2779d3aa1cf)
- 因此，将MD和MD_CHECK改为以下代码，问题解决。
    ![image](https://github.com/user-attachments/assets/15efeb7a-2107-4457-9993-d2f4df9afca2)

**Comment by LucasParker520** [comment]
原因猜测是，我vscode中安装了eide，默认的make工具使用的是eide的make。如果使用mingw32-make，则可以通过。二者区别在于eide的make只能使用sh，使用cmd有时会出错。

**Comment by bobwenstudy** [comment]
很不错，GCC环境确实有不少兼容性问题，作者也是边用边完善

**Comment by bobwenstudy** [comment]
MD_CHECK是为了避免打印一堆warning
WINCMD是为了避免使用了shell环境的make
各个的环境不一样，建议用mingw32-make，谢谢
