### ISSUE TITLE
关于按键矩阵扫描的问题

### ISSUE THREAD

**Issue by AnemosCiel** [bobwenstudy/easy_button#2]
您好，我已经初步移植了代码，移植的挺艰难，但是移植后使用体验很好，感谢作者的开源贡献！
    目前我希望利用这个来制作键盘矩阵扫描，但是有点不太理解该如何将其与ease button结合，这个组件的核心接口是根据ID获取对应按键状态，如果是单个按键，那么我可以在接口中读取IO，返回对应状态，但是矩阵扫描没办法这么做，那是否意味着我需要自行去扫描按键，将状态保存到一个全局变量，接口中返回该变量的对应位？
    另外，动态分配是可以不使用malloc是吗？自行在全局变量定义，然后动态添加到链表？

**Comment by bobwenstudy** [comment]
感谢使用，可以用ebtn_process_with_curr_state接口来做，通过button_get_matrix_key把当前矩阵所有按键+独立按键读取好后，更新到curr_state中，最后将当前状态传给ebtn_process_with_curr_state。
动态分配不理解你表达什么意思

void button_get_key(void)
{
    BIT_ARRAY_DEFINE(curr_state, EBTN_MAX_KEYNUM) = {0};

    button_get_matrix_key(curr_state);

    ebtn_process_with_curr_state(curr_state, get_tick());
}

**Comment by AnemosCiel** [comment]
感谢您的及时回复，是我描述的不够详细。我尝试再更详细的描述一下我的问题。
在移植过程中，我需要自己实现接口函数用于获取按键状态，我实现的接口如下，KEYx_GET()是宏定义，实际是HAL读取GPIO的函数，由于按键是上拉，因此在返回前加了！用于取反。
uint8_t prv_btn_get_state(struct ebtn_btn *btn)
{
    switch(btn->key_id) {
        case USER_BUTTON_0:
            return !KEY1_GET();
        case USER_BUTTON_1:
            return !KEY2_GET();
        case USER_BUTTON_2:
            return !KEY3_GET();
        default:
            return 0;
    }
}
    随后，在固定5ms运行的任务中调用ebtn_process()，内部会自行调用ebtn_get_current_state()根据注册的按键轮询获取状态，然后执行ebtn_process_with_curr_state()来运行状态机判断按键状态，核心原理是通过记录上一次状态并与当前状态异或，也就是常说的三行按键扫描法。
    而在矩阵扫描中，读取电平前多了个设置行为高电平的动作，且通常会希望设置后经过一定延时再读取，因此没办法通过这种宏定义的方式直接返回按键电平，那么我是只能自行实现一个key_scan()函数来轮询采集所有按键的状态，将其对应到全局变量的bit上，然后在prv_btn_get_state()这个接口中，根据ID来返回对应bit的值吗？
    如果按您说的方式来做，那么我不需要实现prv_btn_get_state()这个接口了，也不需要固定5ms调用ebtn_process()，而是需要自行在5ms的轮询中获取状态，然后通过ebtn_process_with_curr_state()接口解析，但这里有个点不太理解，我需要仿照ebtn_get_current_state()函数来根据注册的按键进行扫描吗？还是不用管注册的按键，直接将所有状态获取？比如我将所有按键接入PORTA，那么我可以通过读取PORTA的寄存器一次性获取16个按键的值而不需要轮询获取，或是通过74HC165一次获取8个按键值，即使我没有注册这么多按键？如果需要根据注册按键数量来返回，或许可以通过按键枚举ID最大值来进行mask屏蔽多余的按键，但是组合键同样在枚举ID中，这个我还没想到该如何处理。

    关于第二个问题，我希望组合键并不是在编译阶段确定的，而是通过UART来设置，那么是是不是需要使用ebtn_btn_combo_dyn_t结构来定义一个全局数组，然后在接收到设置指令时，通过ebtn_combo_btn_add_btn()来动态添加按键吗？

**Comment by bobwenstudy** [comment]
如果按您说的方式来做，那么我不需要实现prv_btn_get_state()这个接口了，也不需要固定5ms调用ebtn_process()，而是需要自行在5ms的轮询中获取状态，然后通过ebtn_process_with_curr_state()接口解析
---》是的，不需要实现prv_btn_get_state()这个接口，直接一次性按照id所在bit，设置对应curr_state的bit位。
但这里有个点不太理解，我需要仿照ebtn_get_current_state()函数来根据注册的按键进行扫描吗？还是不用管注册的按键，直接将所有状态获取？
---》是的，不需要一个个按键扫描了，直接按照button ID所在bit位设置对应bit位。

关于第二个问题，我希望组合键并不是在编译阶段确定的，而是通过UART来设置，那么是是不是需要使用ebtn_btn_combo_dyn_t结构来定义一个全局数组，然后在接收到设置指令时，通过ebtn_combo_btn_add_btn()来动态添加按键吗？
---》ebtn_btn_combo_dyn_t是malloc还是全局变量我这边不管，你只管传给我就行
源码不多，建议好好看看源码。邮件你了，可以加微信具体聊，或者直接给你远程处理

**Comment by bobwenstudy** [comment]
可以参考这个代码
```c
static const uint16_t matrix_key_array[3][3] = {
    {USER_BUTTON_0,    USER_BUTTON_3,    USER_BUTTON_6},
    {USER_BUTTON_1,     USER_BUTTON_4,    USER_BUTTON_7},
    {USER_BUTTON_2,     USER_BUTTON_5,   USER_BUTTON_8},
};
static void button_get_matrix_key(bit_array_t* curr_state)
{
    int key_idx;
    for(int row = 0; row < ARRAY_SIZE(matrix_key_row_gpio_array); row ++)
    {
        button_matrix_reset(); 
        if(GPIO_ReadDataBit(matrix_key_row_gpio_array[row]) == 0)
        {
            for(int col = 0; col < ARRAY_SIZE(matrix_key_col_gpio_array); col ++)
            {
                GPIO_WriteBit(matrix_key_col_gpio_array[col], 1);
                if(GPIO_ReadDataBit(matrix_key_row_gpio_array[row]))
                {
                    // get button index
                    key_idx = ebtn_get_btn_index_by_key_id(matrix_key_array[row][col]);
                    if(key_idx >= 0)
                    {
                        // save state
                        bit_array_set(curr_state, key_idx);
                    }
                }
                GPIO_WriteBit(matrix_key_col_gpio_array[col], 0);
            }
        }
    }

    button_matrix_reset();
}
```
